blank_issues_enabled: false
contact_links:
  - name: Hallcrest Engineering Support
    url: https://github.com/jkulba/Orange/discussions
    about: For questions and support, please use our discussions forum
